version: "3.7"

services:
  appsmith-internal-server:
    image: appsmith/appsmith-server:release
    env_file: envs/docker.env
    environment:
      APPSMITH_REDIS_URL: "redis://redis:6379"
      APPSMITH_MONGODB_URI: "mongodb://mongo:27017/appsmith"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    networks:
      - appsmith
    volumes:
      - ./container-volumes/git-storage:/data/git-storage

  mongo:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_DATABASE=appsmith
    volumes:
      - ./container-volumes/mongo:/data/db
    networks:
      - appsmith

  redis:
    image: redis
    networks:
      - appsmith

networks:
  appsmith:
    driver: bridge