[build]
  [build.environment]
    REACT_APP_OAUTH2_GOOGLE_CLIENT_ID = "enabled"
    REACT_APP_OAUTH2_GITHUB_CLIENT_ID = "enabled"
    REACT_APP_OPTIMIZELY_KEY = "Jq3K2kVdvuvxecHyHbVYcj"
    REACT_APP_ALGOLIA_API_ID = "AZ2Z9CJSJ0"
    REACT_APP_ALGOLIA_API_KEY = "d113611dccb80ac14aaa72a6e3ac6d10"
    REACT_APP_ALGOLIA_SEARCH_INDEX_NAME = "test_appsmith"
    REACT_APP_CLIENT_LOG_LEVEL = "debug"
    REACT_APP_GOOGLE_MAPS_API_KEY = "AIzaSyBOQFulljufGt3VDhBAwNjZN09KEFufVyg"
    REACT_APP_TNC_PP = "true"
    REACT_APP_CLOUD_HOSTING = "true"
    REACT_APP_INTERCOM_APP_ID = "y10e7138"
    REACT_APP_MAIL_ENABLED = "true"
    REACT_APP_SENTRY_DSN = "https://95c55da9896c4683913cf7e5c1ec4180@newsentry.appsmith.com/2"
    REACT_APP_SENTRY_ENVIRONMENT = "Production"
    SENTRY_AUTH_TOKEN = "194220827ab64adcb2e3f5e1da2560382f34ac49a84545a597d0309a4e140338"
    SENTRY_URL = "https://newsentry.appsmith.com"
    SENTRY_DSN = "https://95c55da9896c4683913cf7e5c1ec4180@newsentry.appsmith.com/2"
    SENTRY_ORG = "appsmith"
    SENTRY_PROJECT = "appsmith"
    SENTRY_LOG_LEVEL=info


[context.production]
  [context.production.environment]
    REACT_APP_ENVIRONMENT = "PRODUCTION"
    REACT_APP_SENTRY_ENVIRONMENT = "Production"
    REACT_APP_SMART_LOOK_ID = "c370af0df0edf38360adbefbdc47d2b42ea137c9"
    REACT_APP_SEGMENT_KEY = "9OnZ6LnDztuZZo4zXfoutEEBB2wftHUH"
    REACT_APP_BASE_URL = "https://api.appsmith.com"
    APP_HOST = "app.appsmith.com"
    REACT_APP_CLIENT_LOG_LEVEL = "error"

[context.release]
  [context.release.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_SENTRY_ENVIRONMENT = "Staging"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    APP_HOST = "release.app.appsmith.com"

[context.deploy-preview]
  [context.deploy-preview.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_SENTRY_ENVIRONMENT = "Development"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    # Not adding an APP_HOST here because the URL is dynamic in nature and cannot be determined.

[context.develop]
  [context.develop.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    APP_HOST = "develop.app.appsmith.com"

[[headers]]
  for = "/static/*"
  [header.values]
    cache-control = "max-age=604800"

[[redirects]]
  from = "/api/*"
  to = "API_PLACEHOLDER/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/oauth2/*"
  to = "API_PLACEHOLDER/oauth2/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/login/*"
  to = "API_PLACEHOLDER/login/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/f/*"
  to = "https://cdn.optimizely.com/:splat"
  status = 200
  force = true

# This must be the last redirect in the chain because it's a catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
