[build]
  [build.environment]
#    REACT_APP_SENTRY_DSN=
#    REACT_APP_HOTJAR_HJID=
#    REACT_APP_HOTJAR_HJSV=
#    REACT_APP_OAUTH2_GOOGLE_CLIENT_ID=
#    REACT_APP_OAUTH2_GITHUB_CLIENT_ID=
#    REACT_APP_SEGMENT_KEY=
#    REACT_APP_RAPID_API_KEY_VALUE=
#    REACT_APP_OPTIMIZELY_KEY=
#    REACT_APP_ALGOLIA_API_ID=
#    REACT_APP_ALGOLIA_API_KEY=
#    REACT_APP_ALGOLIA_SEARCH_INDEX_NAME=
    REACT_APP_CLIENT_LOG_LEVEL="debug"
#    REACT_APP_GOOGLE_MAPS_API_KEY=


[[headers]]
  for = "/static/*"
  [header.values]
    cache-control = "max-age=604800"

[[redirects]]
  from = "/api/*"
  to = "API_PLACEHOLDER/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/oauth2/*"
  to = "API_PLACEHOLDER/oauth2/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/login/*"
  to = "API_PLACEHOLDER/login/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/f/*"
  to = "https://cdn.optimizely.com/:splat"
  status = 200
  force = true

# This must be the last redirect in the chain because it's a catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200