[build]
  [build.environment]
    REACT_APP_OAUTH2_GOOGLE_CLIENT_ID = "enabled"
    REACT_APP_OAUTH2_GITHUB_CLIENT_ID = "enabled"
    REACT_APP_OPTIMIZELY_KEY = "Jq3K2kVdvuvxecHyHbVYcj"
    REACT_APP_ALGOLIA_API_ID = "AZ2Z9CJSJ0"
    REACT_APP_ALGOLIA_API_KEY = "d113611dccb80ac14aaa72a6e3ac6d10"
    REACT_APP_ALGOLIA_SEARCH_INDEX_NAME = "test_appsmith"
    REACT_APP_CLIENT_LOG_LEVEL = "debug"
    REACT_APP_GOOGLE_MAPS_API_KEY = "AIzaSyBOQFulljufGt3VDhBAwNjZN09KEFufVyg"
    REACT_APP_GOOGLE_RECAPTCHA_SITE_KEY = ""
    REACT_APP_TNC_PP = "true"
    REACT_APP_CLOUD_HOSTING = "true"
    REACT_APP_INTERCOM_APP_ID = "y10e7138"
    REACT_APP_MAIL_ENABLED = "true"
    REACT_APP_SENTRY_DSN = "https://abf15a075d1347969df44c746cca7eaa@o296332.ingest.sentry.io/1546547"
    REACT_APP_SENTRY_ENVIRONMENT = "Production"
    REACT_APP_SHOW_ONBOARDING_FORM = "true"
    SENTRY_AUTH_TOKEN = "dfdf7fa46c5b483a944b4571554d6466da3c64a6ed8b46e3b8a4285183a6bcc3"
    SENTRY_DSN = "https://abf15a075d1347969df44c746cca7eaa@o296332.ingest.sentry.io/1546547"
    SENTRY_ORG = "appsmith"
    SENTRY_PROJECT = "appsmith"
    SENTRY_LOG_LEVEL = "info"

[context.deploy-preview]
  [context.deploy-preview.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_SENTRY_ENVIRONMENT = "Development"
    REACT_APP_BASE_URL = "https://release.app.appsmith.com"
    # Not adding an APP_HOST here because the URL is dynamic in nature and cannot be determined.

[context.develop]
  [context.develop.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_BASE_URL = "https://release.app.appsmith.com"
    APP_HOST = "develop.app.appsmith.com"

[[headers]]
  for = "/static/*"
  [header.values]
    cache-control = "max-age=604800"

[[redirects]]
  from = "/api/*"
  to = "API_PLACEHOLDER/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/oauth2/*"
  to = "API_PLACEHOLDER/oauth2/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/login/*"
  to = "API_PLACEHOLDER/login/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/f/*"
  to = "https://cdn.optimizely.com/:splat"
  status = 200
  force = true

# This must be the last redirect in the chain because it's a catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
