apiVersion: v1
kind: Service
metadata:
  name: appsmith-service
  labels:
    app: appsmith-service
spec:
  type: ClusterIP
  selector:
    app: appsmith
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: appsmith
spec:
  selector:
    matchLabels:
      app: appsmith
  serviceName: "appsmith-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: appsmith
    spec:
      containers:
      - name: appsmith
        image: appsmith/appsmith-ce:latest
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: application-config
          - configMapRef:
              name: encryption-config
        volumeMounts:
          - name: appsmith-data
            mountPath: /appsmith-stacks
  volumeClaimTemplates:
  - metadata:
      name: appsmith-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi