---
user_email: 'youremail@gmail.com'
install_dir: ''
mongo_host: 'mongo'
mongo_root_user: ''
mongo_root_password: ''
mongo_database: 'appsmith'
user_encryption_password: ''
user_encryption_salt: ''
custom_domain: ''
ssl_enable: 'false'
letsencrypt_email: 'youremail@gmail.com'
is_ssl_staging: 'false'
disable_telemetry: 'true'
mail_enabled: 'false'
mail_from: ''
mail_to: ''
mail_host: ''
mail_port: '' 
mail_ssl_enabled: 'false'
mail_username: ''
mail_password: ''
mail_auth: ''
google_client_id: ''
google_secret_id: ''
github_client_id: ''
github_secret_id: ''
google_maps_api_key: ''
sentry_dns: ''
smart_look_id: ''
marketplace_enabled: 'false'
segment_key: ''
optimizely_key: ''
algolia_api_id: ''
algolia_search_index_name: ''
algolia_api_key: ''
client_log_level: ''
tnc_pp: ''
version_id: ''
version_release_date: ''
intercom_app_id: ''
google_recaptcha_site_key: ''
google_recaptcha_secret_key: ''
google_recaptcha_enabled: 'false'
disable_intercom: 'false'
