name: "Super Labeler"
on:
  issues:
    types: [labeled, opened, edited, closed, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Videndum/label-mastermind@2.0.0

        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
