name: "Project Labeler"
on:
  issues:
    types:
      - assigned
      - opened
      - edited
  project_card:
    types:
      - converted
      - moved
      - deleted
      - created

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels by project
        uses: d-i-bondarenko/project-labeler@v0.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
